config/routes.rb
Rails.application.routes.draw do

  namespace :words do
    get "index"
    post "submit"
    get "about"
  end

  root "words#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/words_controller.rb
# I'm just using one controller for everything, because there's no point making
# a static page controller for one page.
# @author psyomn
class WordsController < ApplicationController
  include CustomDataStructures

  def index
  end

  # The algorithmic part of the controller is factored out in lib/
  def submit
    file = params["words_list"]
    flash.clear
    begin
      @results = WordTree.new(file.read).process
    rescue WordTreeError
      flash[:word_tree_error] = "Unable to find a stacked word tree :("
    rescue BadFileError
      flash[:bad_file_error] = "You have uploaded an incompatible file!"
    rescue
      flash[:error] = "An unexpected error has occured. Contact site admin."
    end
    render layout: false
  end

  def about
    @ascii_to_vec = CodeRay.scan("
def string_to_vec(str)
  arr = Array.new(26, 0)
  str.chars.map { |e| arr[e.ord - 97] += 1 }
  arr
end", :ruby).div(line_numbers: :table)

    @ascii_inject = CodeRay.scan("
def matrix_successor?(m1, m2)
  ((0...26).inject(0) { |sum,el| (m1[el] - m2[el]).abs + sum }) == 1
end
", :ruby).div(line_numbers: :table)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Words</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <h1> Words Application </h1>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container-fluid">
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", words_index_path %></li>
            <li><%= link_to "About", words_about_path %></li>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
  </div>
</body>
</html>

app/views/words/about.html.erb
<h1> About / Report </h1>

<p> This is the assignment given to me (<%= link_to "Simon Symeonidis (cv.pdf)", "/cv-2016.pdf" %>)
by AdGear after the interview. The problem is the word stack problem, which
requires an algorithm to find words with similar letters but one difference to
stack against each other, until the final term of size 3 is found.</p>

<p> There's a few ways one can do this, but I chose some particular paths. </p>

<h2> Algorithm </h2>
<h3> Optimizations (Gross) </h3>

<p> My initial algorithm was too slow. The reason was because I was trying to do
set differences against the letters. This would comprise of splitting words, and
performing the set difference, and finding if there were any extra letters. I
ended up scrapping this approach, and went with a more optimal one. </p>

<p> Let's think back. What are anagrams? Anagrams are essentially words, with
the same amount of letters, but reorganized. So essentially, if you were to
represent two anagrams as vectors, and calculate their difference, you would end
up with a zero sum. In the exercise however, there's an extra letter, so we may
expect the terms to yield a sum of 1.</p>

<p> In order to increase performance, I split the characters of the words, and
represented them as vectors. You can see it in the snippet below.  </p>

<%= raw(@ascii_to_vec) %>

<p> So if you had a string "aaab", and "baaa" you would get [3,1] for both. If you
then represented both as vectors v<sub>1</sub>, and v<sub>2</sub>, and
calculated their absolute difference, you would get a vector that gets folded to 0.
But, again, in the case of this example, the sum would default to one due to the
extra letter. We can observe the method that does this check here:
</p>

<%= raw(@ascii_inject) %>

<p> This small trick significantly improved performance on my computer (though I
did not keep stats of previous runs...). </p>

<h3> Optimizations (Smaller) </h3>

<p> Stacked words have the distinct property that each successor is one size
bigger than the previous one. This gives us the opportunity to remove words
which break the indexing.</p>

<p> What we mean with the above is, say we have words grouped in sizes of [3, 4,
5, 6, 7, 9, 10, 11, 12]. The index skips from 7 to 9. There will never be words
stacking in that case, so we are free to remove words with size 9 and greater,
further speeding up the algorithm in fringe cases. </p>

<h3> How the Tree Works </h3>

<p> Before running the algorithm, I group all the words provided in the file, by
word size. I also apply the above preprocessing techniques I described (removing
skips, and vectorizing words). This allows me to look from greatest, and find
possible successors, until I find the last term of size 3.
</p>

<p> I use a tree data structure. At the root, I start with the largest word, and
run the successor check against terms which are smaller by 1, from the current
term. If any are found, they're added as chidlren, and the successor check runs on
those as well. If the algorithm hits a dead end, it backtracks to the last child
of a parent node, somewhere at the top of the hierarchy, and reapplies the
successor checks, until a result is found, or all possible successors are exhausted.
It is important to stress <i>that I'm not generating the whole tree with
  successors</i>. I'm generating it along the way.
</p>

<h3> Conclusion </h3>
<p> It has been a pleasant exercise! Hope to hear from you soon. </p>

app/views/words/index.html.erb
<h1> Words File Upload </h1>

<div class="panel-default">
  <div class="panel-heading">
    Please upload the file with the word lists here.
  </div>
  <div class="panel-body">
    <%= form_tag({action: :submit}, html: {multipart: true}, remote: true, id: 'myform') do %>
      <div class="form-group">
        <div class="row">
          <div class="col-sm-4">
            <%= file_field_tag 'words_list', class: 'file' %>
          </div>
          <div class="col-sm-2">
            <%= submit_tag 'submit file', class: 'btn btn-default' %>
          </div>
        </div>
      </div>
    <% end %>

    <div id="word-spinner">Crunching hard numbers... please wait...</div>
    <div id="response-box"></div>
    <div id="try-again" style="display:hidden;" class="btn btn-primary">Upload Another File?</div>
  </div>
</div>

app/views/words/submit.html.erb
<% if !(flash[:bad_file_error]) && !(flash[:word_tree_error]) %>
  <h1> Submission Results </h1>

  <p> Here are the results. </p>

  <ul>
    <% @results.each do |word| %>
      <li> <%= word %> </li>
    <% end %>
  </ul>
<% elsif v = flash[:bad_file_error] %>
  <h1> Bad File! </h1>
  <p> <%= v %> </p>
  <p> Some things to keep in mind: </p>
  <ul>
    <li> Make sure that your file is plain ASCII </li>
    <li> Make sure you're not uploading an empty file </li>
    <li> Make sure that you're not uploading a file full of whitespaces! </li>
    <li> Make sure you're not uploading binary/data files </li>
  </ul>
<% elsif v = flash[:word_tree_error] %>
  <h1> No Word Tree! </h1>
  <p> <%= v %> </p>
<% end %>